name: Run E2E tests
on:
  workflow_run:
    workflows: ["deploy"]
    types:
      - completed
    branches-ignore:
      - "livekit"
jobs:
  e2e:
    name: E2E tests runs on Element Call
    runs-on: ubuntu-latest
    steps:
      - name: Check out test private repo
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
        with:
          repository: element-hq/static-call-participant
          ref: refs/heads/main
          path: static-call-participant
          token: ${{ secrets.GH_E2E_TEST_TOKEN }}
      - name: Build E2E Image
        run: "cd static-call-participant && docker build --no-cache --tag matrixdotorg/chrome-node-static-call-participant:latest ."
      - name: Run E2E tests in container
        run: "docker run --rm -v '${{ github.workspace }}/static-call-participant/callemshost-users.txt:/opt/app/callemshost-users.txt' matrixdotorg/chrome-node-static-call-participant:latest ./e2e.sh"
