name: Lint, format & type check
on:
  pull_request: {}
jobs:
  prettier:
    name: Lint, format & type check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Yarn cache
        uses: actions/setup-node@v4
        with:
          cache: "yarn"
      - name: Install dependencies
        run: "yarn install"
      - name: Prettier
        run: "yarn run prettier:check"
      - name: i18n
        run: "yarn run i18n:check"
      - name: ESLint
        run: "yarn run lint:eslint"
      - name: Type check
        run: "yarn run lint:types"
